# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['say_hello', 'foo']

# %% ../nbs/00_core.ipynb 1
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'

say_hello("Isaac")

# %% ../nbs/00_core.ipynb 3
def foo(): pass
